service: image-processing-tool

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-1
  tags:
    project: image-processing-tool
  httpApi:
    useProviderTags: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource: 'arn:aws:s3:::ffffffffffffff/*'
        - Effect: Allow
          Action: 'rekognition:*'
          Resource: '*'
        - Effect: Allow
          Action: 'textract:*'
          Resource: '*'

functions:
  uploadfile:
    handler: lambda/uploadfile/index.handler
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /uploadfile
          method: post

  editimage:
    handler: lambda/editimage/index.handler
    memorySize: 2048
    timeout: 28
    layers:
      - arn:aws:lambda:eu-west-1:ffffffffffff:layer:sharp-linux:1
      - arn:aws:lambda:eu-west-1:ffffffffffff:layer:request-node:1
    events:
      - httpApi:
          path: /editimage
          method: post
